### ISSUE TITLE
Labels not drawn if density calculation fails due to few points

### ISSUE THREAD

**Issue by mschubert** [aphalo/ggpp#32]
I've run into an issue where `stat_dens2d_filter` does not draw labels although they satisfy the requirements specified by `keep.fraction` and `keep.number`.

A simple example would be the following:

```r
ggplot(data.frame(x=1,y=1,label="label"), aes(x=x,y=y)) +
    geom_point() +
    ggpp::stat_dens2d_filter(aes(label=label), geom="text", keep.number=Inf, keep.fraction=1)
# Warning messages:
# Computation failed in `stat_dens2d_filter()`
# Caused by error in `if (any(h <= 0)) ...`:
# ! missing value where TRUE/FALSE needed
```

![image](https://user-images.githubusercontent.com/442360/219141860-e98dd746-3075-4a25-a6bc-0352da74f776.png)

Maybe it's worth skipping the density calculation if there are fewer points in the data set than should pass the filter?

**Comment by aphalo** [comment]
Thanks! No doubt a clearer error/warning message is needed. I think the best approach would be passing all data with a warning.

**Comment by aphalo** [comment]
@mschubert I have now fixed this in `stat_dens1d_filter()` and will look at `stat_dens2d_filter()` in the evening. For `stat_dens1d_filter()` there is no need for a warning, as density estimate fails only when `n < 2` in which case the filtering can be done based on testing if `keep.fraction >= 0.5`.

**Comment by aphalo** [comment]
@mschubert Thanks again! Now the same fix is implemented in all the `stat_dens1d_...()` and `stat_dens2d_...()` functions. Can you please test if the version here in GitHub solves the problem in your actual use case, and if yes, close this issue. Otherwise, please, let me know here that the problem persists.

**Comment by mschubert** [comment]
Thank you for your quick response! This now works for one point, but still fails if I add a second point:

```r
ggplot(data.frame(x=c(-1,1),y=1,label="label"), aes(x=x,y=y)) +
    geom_point() +
    ggpp::stat_dens2d_filter(aes(label=label), geom="text", keep.number=Inf, keep.fraction=1)

```

**Comment by aphalo** [comment]
@mschubert Thanks! This then seems to depend on which two values they are, or maybe I failed to test this case properly... Will have a look.

**Comment by aphalo** [comment]
@mschubert o.k., now I understand, the two `y` values in your example are identical, preventing the computation of bandwidth. This is also a special case.

**Comment by aphalo** [comment]
@mschubert I got this far: if the density cannot be computed, then labels are shown only if `keep.fraction = 1`, which is the expect behaviour for a single observation. If the density cannot be computed but we have more than one row in data, the behaviour is the same, except that a message tells that the density could not be computed. In the second example below no density can be computed along the y axis, so there is no consistent way of choosing one of the two observations.

Unless this is crucial, I would rather not add special handling based on a single axis as a fall back. It can be done but would make the code more complex.

``` r
library(ggpp)
#> Loading required package: ggplot2
#> 
#> Attaching package: 'ggpp'
#> The following object is masked from 'package:ggplot2':
#> 
#>     annotate

ggplot(data.frame(x=c(-1,1),y=1,label="label"), aes(x=x,y=y)) +
  geom_point() +
  ggpp::stat_dens2d_filter(aes(label=label), geom="text", keep.number=Inf, keep.fraction=1)
#> Density not computed, too few distinct values in 'x' and/or 'y'
```

![](https://i.imgur.com/mNkdr3F.png)

``` r


ggplot(data.frame(x=c(-1,1),y=1,label="label"), aes(x=x,y=y)) +
  geom_point() +
  ggpp::stat_dens2d_filter(aes(label=label), geom="text", keep.number=Inf, keep.fraction=0.5)
#> Density not computed, too few distinct values in 'x' and/or 'y'
```

![](https://i.imgur.com/zXnUrjx.png)

<sup>Created on 2023-02-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by aphalo** [comment]
@mschubert I close this issue as this case no longer triggers an error, please, reopen this issue if you have additional ideas about this. When the 2D density cannot be estimated one solution would be to compute a 1D density when possible. I do not like this approach, as it would make the returned value inconsistent with non-exceptional 2D cases. If I implement this, it would not be the default behaviour.

**Comment by mschubert** [comment]
I just tested this and it fixes the "real life" use cases I had issues with.

Thank you, especially for looking at this so quickly! :rocket:
